### PR TITLE
cash-register

### PR DESCRIPTION
**Pull request by Nooria150**
Summary

Implement change calculation functionality for cash transactions.

Changes Made

Added logic to compute change based on item price and cash provided.
Updated UI to display calculated change and transaction status.

### CODE REVIEW

**Comment by Nooria150** [comment]
@ahzamir
I have done my project because the lack of time I couldn't mentioned my partners.

**Comment by ahzamir** [comment]
@Nooria150 

Mention your partner we have time!

**Comment by Nooria150** [comment]
@iamfarhatsharefi @Saqibi4213
could you please review my code.

**Comment by Saqibi4213** [comment]
> @iamfarhatsharefi @Saqibi4213 could you please review my code.

well done nooria but still your freecodecamp dont pass all requirment need one other option 
Screenshot (93)

**Comment by Nooria150** [comment]
@Saqibi4213 @iamfarhatsharefi
thank you for the review.
I implement your feedback.

**Comment by Nooria150** [comment]
@ahzamir could you please check my project?

**Review by ahzamir — CHANGES_REQUESTED** [review]
@Nooria150 
- Well done, you have implemented most of the requirements but still your project misses some small requirements:
  - You have to show the user the total price.
  - You have to show the number of cash in the drawer.

- Please have a look at this [example](https://cash-register.freecodecamp.rocks/) your app should be same like this:
image
image

**Comment by Nooria150** [comment]
@ahzamir 
I implement the feedback
could you please check it

**Review by ahzamir — APPROVED** [review]
### Hi @Nooria150 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Cash Register project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Comment by Nooria150** [comment]
@ahzamir thank you for approving but still the deploy link is not working so I am going to merge it after that i will try again.

**Pull request merged**
